# Generated by Django 5.1.7 on 2025-03-09 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("Boxing", "Boxing"),
                            ("Kickboxing", "Kickboxing"),
                            ("BJJ", "Brazilian Jiu-Jitsu"),
                            ("Wrestling", "Wrestling"),
                            ("Muay Thai", "Muay Thai"),
                            ("MMA", "Mixed Martial Arts"),
                            ("Conditioning", "Strength & Conditioning"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("notes", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
